/**
 * Car inventory data — 12 realistic Bay Area listings sourced from
 * actual CarMax SF Bay Area inventory patterns (mid-2025 pricing).
 *
 * Fields:
 *   id        – slug used for routing and image lookup (/public/cars/<id>.jpg)
 *   fit       – 0–100 match score vs. the prototype buyer brief
 *   deal      – 'Good' | 'Fair' | 'Over' (vs. market comparables)
 *   tco       – estimated monthly total cost of ownership (insurance + gas/charging + maintenance)
 *   otd       – out-the-door asking price
 *   dealDelta – price difference vs. market (e.g. '−$800')
 *   dealComps – number of comparable listings used (e.g. '14 comps')
 *   mustHaveKeys – which mustHave keys this car satisfies (awd, carplay, backup, mpg, thirdrow, manual)
 *   tradeoff  – one-line tradeoff vs. the top pick
 */

export interface CarListing {
  id: string;
  name: string;
  miles: string;
  distance: string;
  fit: number;
  deal: 'Good' | 'Fair' | 'Over';
  tco: string;
  otd: string;
  condition: 'New' | 'Certified pre-owned' | 'Used';
  fuelType: 'Gas' | 'Hybrid' | 'Electric';
  dealer: string;
  pros: string[];
  cons: string[];
  why: string;
  dealDelta: string;
  dealComps: string;
  mustHaveKeys: string[];
  tradeoff?: string;
  imageUrl: string;
}

// Replace 'try' with your Imagin.Studio customer ID (free trial at imagin.studio)
const IMAGIN = (make: string, model: string, year: number) =>
  `https://cdn.imagin.studio/getimage?customer=try&make=${make}&modelFamily=${model}&modelYear=${year}&angle=side`;

export const carListings: CarListing[] = [
  {
    id: 'crv22',
    name: '2022 Honda CR-V EX',
    miles: '29k mi',
    distance: '18 mi away',
    fit: 91,
    deal: 'Good',
    tco: '$435',
    otd: '$28,490',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'CarMax Fremont',
    pros: [
      'Bulletproof reliability — #1 in its class for 3+ years',
      'Roomy cargo with hands-free liftgate',
      'Holds value better than most rivals',
    ],
    cons: ['Underwhelming to drive', 'Smaller rear seat than RAV4'],
    why: "This is the safest pick for someone who ranked reliability first. The 2022 CR-V had zero major recalls and owners routinely keep them past 150k miles. This one is a one-owner CarMax CPO with a 90-day warranty layered on top of the remaining factory coverage. It's priced $800 below comparable listings in the area.",
    dealDelta: '−$800',
    dealComps: '14 comps',
    mustHaveKeys: ['carplay', 'backup'],
    imageUrl: IMAGIN('honda', 'cr-v', 2022),
  },
  {
    id: 'rav4xle',
    name: '2021 Toyota RAV4 XLE',
    miles: '36k mi',
    distance: '24 mi away',
    fit: 87,
    deal: 'Fair',
    tco: '$455',
    otd: '$29,850',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'CarMax Oakland',
    pros: [
      'Top-tier long-term reliability (J.D. Power #1)',
      'More rear legroom than most crossovers',
      'Strong resale — retains ~58% after 3 years',
    ],
    cons: ['Priced at market, not a bargain right now', 'Base XLE trim lacks wireless CarPlay'],
    why: "The RAV4 is every bit as dependable as the CR-V — some years even better — and has more rear legroom. The catch is the Bay Area market is running hot on RAV4s right now, so this one is priced at fair value, not below it. I'd watch it for a week before making an offer; RAV4 prices have been drifting down about 2% per month.",
    dealDelta: '+$200',
    dealComps: '18 comps',
    mustHaveKeys: ['backup'],
    tradeoff: 'More legroom than CR-V but priced at market, not below it',
    imageUrl: IMAGIN('toyota', 'rav4', 2021),
  },
  {
    id: 'cx522',
    name: '2022 Mazda CX-5 Touring',
    miles: '23k mi',
    distance: '28 mi away',
    fit: 84,
    deal: 'Good',
    tco: '$390',
    otd: '$26,700',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Bay City Motors · Burlingame',
    pros: [
      'Best driving dynamics in this price range',
      'Interior quality punches above the price tag',
      'Lowest monthly cost on your list',
    ],
    cons: ['Rear seat tighter than RAV4/CR-V', 'Reliability good but not Honda/Toyota tier'],
    why: "If you care even a little about how a car feels to drive, test this one first. The CX-5 has a chassis that most SUVs twice the price can't match, and the cabin materials feel closer to a $40k car. It scores a bit lower here only because reliability is one step below the Japanese-brand benchmark — still excellent, just not class-leading.",
    dealDelta: '−$1,100',
    dealComps: '12 comps',
    mustHaveKeys: ['carplay', 'backup'],
    tradeoff: 'Best to drive but rear seat tighter and reliability one tier below Honda/Toyota',
    imageUrl: IMAGIN('mazda', 'cx-5', 2022),
  },
  {
    id: 'niroev23',
    name: '2023 Kia Niro EV Wind',
    miles: '9k mi',
    distance: '15 mi away',
    fit: 83,
    deal: 'Good',
    tco: '$395',
    otd: '$30,500',
    condition: 'Used',
    fuelType: 'Electric',
    dealer: 'Serramonte Kia · Colma',
    pros: [
      'Cheapest to run if you charge at home (~$35/mo in electricity)',
      'Almost new — full factory warranty still active',
      'No oil changes or brake jobs for years',
    ],
    cons: ['253-mile EPA range (fine for commute, tight for road trips)', 'Public fast-charging adds ~$30–50/mo if you rely on it'],
    why: "This is the dark-horse pick. It's essentially a new car — one prior owner put 9k miles on it before trading up — with Kia's 10-year powertrain warranty still fully intact. If you can plug in at home, your monthly running cost drops well below every gas car on this list. The $30,500 asking price already reflects the $3,750 used EV federal tax credit.",
    dealDelta: '−$950',
    dealComps: '9 comps',
    mustHaveKeys: ['carplay', 'backup', 'mpg'],
    tradeoff: 'Lowest running cost but range limits longer road trips without planning',
    imageUrl: IMAGIN('kia', 'niro', 2023),
  },
  {
    id: 'escape22h',
    name: '2022 Ford Escape SE Hybrid',
    miles: '27k mi',
    distance: '33 mi away',
    fit: 82,
    deal: 'Good',
    tco: '$400',
    otd: '$25,900',
    condition: 'Certified pre-owned',
    fuelType: 'Hybrid',
    dealer: 'CarMax San Rafael',
    pros: [
      '42 mpg combined — best fuel economy of non-EV options',
      'CPO warranty through CarMax covers 90 days bumper-to-bumper',
      'Comfortable, compliant ride on Bay Area roads',
    ],
    cons: ['Ford long-term reliability trails Toyota/Honda', 'Cargo floor sits higher than rivals'],
    why: "A solid middle-ground choice: hybrid efficiency without the range anxiety of full electric, and priced meaningfully below the RAV4 hybrid. The Ford reliability caveat is real — Consumer Reports shows the Escape Hybrid slightly below average — but the CPO coverage gives you a buffer. Worth a test drive if fuel costs are a priority.",
    dealDelta: '−$600',
    dealComps: '11 comps',
    mustHaveKeys: ['carplay', 'backup', 'mpg'],
    tradeoff: 'Best hybrid mpg at the lowest price, but Ford reliability lags Toyota/Honda long-term',
    imageUrl: IMAGIN('ford', 'escape', 2022),
  },
  {
    id: 'tucson23h',
    name: '2023 Hyundai Tucson Hybrid SEL',
    miles: '14k mi',
    distance: '26 mi away',
    fit: 80,
    deal: 'Fair',
    tco: '$430',
    otd: '$31,800',
    condition: 'Certified pre-owned',
    fuelType: 'Hybrid',
    dealer: 'CarMax Oakland',
    pros: [
      'Very nearly new — 1 year old, 38 mi/gallon combined',
      'Loaded with standard safety features (Highway Driving Assist II)',
      'Panoramic sunroof standard at this trim',
    ],
    cons: ['At the top of your budget range', 'Hyundai reliability improving but not Toyota-tier yet'],
    why: "The Tucson Hybrid is genuinely excellent — Hyundai has closed the reliability gap significantly in the 2022+ generation. This one is practically new and fully loaded. It scores Fair on deal because you're paying close to market rate; if your budget was firmer at $28k I'd skip it, but at $31,800 with this mileage you're getting more car per dollar than most of the options here.",
    dealDelta: '+$350',
    dealComps: '10 comps',
    mustHaveKeys: ['carplay', 'backup', 'mpg'],
    tradeoff: 'Most features per dollar but stretches the budget and priced at market',
    imageUrl: IMAGIN('hyundai', 'tucson', 2023),
  },
  {
    id: 'outback22',
    name: '2022 Subaru Outback Wilderness',
    miles: '24k mi',
    distance: '38 mi away',
    fit: 81,
    deal: 'Good',
    tco: '$465',
    otd: '$33,400',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'Golden Gate Subaru · SF',
    pros: [
      'Standard AWD with 9.5" ground clearance — genuinely capable off-road',
      'One of the roomiest interiors in this class',
      'Subaru CPO adds 7-year/100k powertrain warranty',
    ],
    cons: ['Near your budget ceiling', '23 mpg combined — thirstier than rivals', 'Dealer is 38 miles away'],
    why: "If you care about AWD or want something that handles Bay Area winters and the occasional Tahoe trip confidently, the Wilderness trim is uniquely capable at this price. The trade-off is fuel cost — running about $65/mo more than the CX-5 — and it stretches to the top of your budget. The CPO warranty is very comprehensive though.",
    dealDelta: '−$700',
    dealComps: '8 comps',
    mustHaveKeys: ['awd', 'backup'],
    tradeoff: 'Only true off-road pick in the list but fuel cost runs $65/mo higher than average',
    imageUrl: IMAGIN('subaru', 'outback', 2022),
  },
  {
    id: 'camry22',
    name: '2022 Toyota Camry SE',
    miles: '28k mi',
    distance: '19 mi away',
    fit: 78,
    deal: 'Fair',
    tco: '$415',
    otd: '$25,500',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'CarMax Fremont',
    pros: [
      'Toyota reliability — expect 200k+ miles with normal maintenance',
      'Silky smooth highway cruiser, ultra-quiet cabin',
      'Excellent resale value',
    ],
    cons: ['Sedan — no extra cargo height vs. crossovers', 'AWD not available in this generation'],
    why: "The Camry scores lower here mainly because it's a sedan and your brief mentioned needing cargo space. If that's flexible, this is a deeply reliable car at a fair price — Toyota's near-perfect ownership record on the Camry is hard to argue with. Priced at market right now, so there's not much negotiating room.",
    dealDelta: '+$100',
    dealComps: '21 comps',
    mustHaveKeys: ['carplay', 'backup'],
    tradeoff: 'Toyota reliability at a lower price, but sedan limits cargo vs. every crossover here',
    imageUrl: IMAGIN('toyota', 'camry', 2022),
  },
  {
    id: 'civic21',
    name: '2021 Honda Civic Sport',
    miles: '31k mi',
    distance: '12 mi away',
    fit: 77,
    deal: 'Good',
    tco: '$380',
    otd: '$22,800',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Peninsula Honda · San Mateo',
    pros: [
      'Lowest out-the-door price on your list',
      '32 mpg combined, lowest fuel cost of the gas options',
      'Fun to drive — responsive steering, better than the Camry',
    ],
    cons: ['Compact sedan — less cargo space than any crossover here', 'Rear seat tight for car seats'],
    why: "The best pick if budget is the primary filter. At $22,800 you're paying $6k less than the CR-V with nearly the same reliability DNA. The Civic scores lower here because you mentioned cargo being a factor. But if you reconsider the sedan vs. SUV question, this car will cost you less to own over 5 years than anything else on this list.",
    dealDelta: '−$1,300',
    dealComps: '16 comps',
    mustHaveKeys: ['carplay', 'backup'],
    tradeoff: 'Lowest 5-year ownership cost but cargo space is the clear sacrifice vs. any crossover',
    imageUrl: IMAGIN('honda', 'civic', 2021),
  },
  {
    id: 'forester22',
    name: '2022 Subaru Forester Sport',
    miles: '34k mi',
    distance: '22 mi away',
    fit: 76,
    deal: 'Fair',
    tco: '$450',
    otd: '$27,500',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'Golden Gate Subaru · SF',
    pros: [
      'Standard AWD, best-in-class visibility',
      'Tall roofline — easiest car to get kids in and out of',
      'CPO warranty: 7 years / 100k miles powertrain',
    ],
    cons: ['CVT transmission polarizing for driving feel', 'Priced at market — little room to negotiate'],
    why: "The Forester is the choice if AWD and easy entry/exit matter most — it's the tallest SUV here and has the sightlines of a truck without the size. Scored Fair on deal because Golden Gate Subaru's CPO pricing is firm. If reliability is the priority, I'd pick the CR-V; if AWD is the priority and you want a Bay dealer, this is the pick.",
    dealDelta: '+$250',
    dealComps: '13 comps',
    mustHaveKeys: ['awd', 'backup'],
    tradeoff: 'Best AWD value with 7-yr CPO warranty but driving feel and pricing are compromises',
    imageUrl: IMAGIN('subaru', 'forester', 2022),
  },
  {
    id: 'equinox22',
    name: '2022 Chevrolet Equinox LT AWD',
    miles: '32k mi',
    distance: '29 mi away',
    fit: 73,
    deal: 'Good',
    tco: '$440',
    otd: '$23,500',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'CarMax Serramonte',
    pros: [
      'AWD at one of the lowest prices on the list',
      'CarMax CPO — 90-day worry-free return policy',
      'More standard safety tech than CR-V at this price',
    ],
    cons: ['GM reliability below Japanese rivals (Consumer Reports below average)', 'Resale value drops faster — worth ~45% in 3 years vs. 58% for RAV4'],
    why: "The Equinox scores lower here because long-term reliability is a real gap compared to Honda and Toyota. That said, at $23,500 with AWD and CarMax's CPO coverage it's genuinely hard to ignore on price. If you're planning to keep the car under 4 years, the reliability delta matters less. If you're in it for 7+ years, I'd spend the extra $5k on the CR-V.",
    dealDelta: '−$1,500',
    dealComps: '15 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup'],
    tradeoff: 'Cheapest AWD option but reliability and resale both trail Japanese rivals meaningfully',
    imageUrl: IMAGIN('chevrolet', 'equinox', 2022),
  },
  {
    id: 'rogue20',
    name: '2020 Nissan Rogue SV AWD',
    miles: '48k mi',
    distance: '16 mi away',
    fit: 71,
    deal: 'Good',
    tco: '$420',
    otd: '$19,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Private Seller · Oakland',
    pros: [
      'Lowest asking price on the list — $3,600 below next cheapest',
      'AWD standard, decent cargo space',
      'Zero dealer fees (private sale)',
    ],
    cons: [
      '2020 Rogue CVT had documented reliability issues — check service history',
      'Higher miles means you\'re closer to first major maintenance costs',
      'Private sale: no CPO warranty, no return policy',
    ],
    why: "The lowest price, but I'm flagging two things: the 2020 Rogue's CVT (transmission) had elevated failure rates in that model year — it's the #1 thing to verify before buying. Get a pre-purchase inspection at an independent shop (~$150) and pull the Carfax. If it passes, the $19,900 is genuinely good value. If that comes back messy, walk away — there's no warranty to catch you.",
    dealDelta: '−$2,200',
    dealComps: '19 comps',
    mustHaveKeys: ['awd', 'backup'],
    tradeoff: 'Best price by far but CVT reliability risk on this model year requires a PPI before buying',
    imageUrl: IMAGIN('nissan', 'rogue', 2020),
  },
  {
    id: 'accord22',
    name: '2022 Honda Accord Sport',
    miles: '26k mi',
    distance: '21 mi away',
    fit: 88,
    deal: 'Good',
    tco: '$410',
    otd: '$26,400',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'CarMax Fremont',
    pros: ['Consistently tops reliability surveys among midsize sedans', 'Roomier rear seat and trunk than most competitors', 'Sport trim adds paddle shifters and a firmer suspension without hurting the ride'],
    cons: ['Sedan body limits cargo versus a crossover', '1.5L turbo wants premium fuel for peak output'],
    why: 'The Accord is the sedan equivalent of the CR-V — Honda\'s reliability data on this generation is excellent, and the Sport trim adds some driving engagement without sacrificing comfort. It\'s priced about $500 under comparable Bay Area listings.',
    dealDelta: '−$500',
    dealComps: '17 comps',
    mustHaveKeys: ['carplay', 'backup'],
    tradeoff: 'More engaging to drive than Camry/CR-V but a sedan trunk instead of crossover cargo',
    imageUrl: IMAGIN('honda', 'accord', 2022),
  },
  {
    id: 'corolla21',
    name: '2021 Toyota Corolla SE',
    miles: '34k mi',
    distance: '14 mi away',
    fit: 74,
    deal: 'Good',
    tco: '$340',
    otd: '$19,600',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'CarMax San Jose',
    pros: ['Lowest running cost of any gas sedan on the list', 'Toyota reliability — this generation has an excellent track record', 'Standard Toyota Safety Sense 2.0 (adaptive cruise, lane keep)'],
    cons: ['Rear seat and trunk are tight for a family', 'Base engine feels underpowered on freeway on-ramps'],
    why: 'If price is the main filter, the Corolla is hard to beat — it\'s $2,000+ below the Civic on this list with nearly identical Toyota-grade reliability. It\'s not exciting to drive, but it\'s the cheapest car here to own over 5 years.',
    dealDelta: '−$650',
    dealComps: '20 comps',
    mustHaveKeys: ['carplay', 'backup'],
    tradeoff: 'Cheapest car on the list to own long-term but the smallest interior',
    imageUrl: IMAGIN('toyota', 'corolla', 2021),
  },
  {
    id: 'altima20',
    name: '2020 Nissan Altima SV',
    miles: '42k mi',
    distance: '27 mi away',
    fit: 66,
    deal: 'Good',
    tco: '$360',
    otd: '$17,800',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Private Seller · San Jose',
    pros: ['Lowest price of any sedan on the list', 'Spacious cabin, class-leading rear legroom', 'Available AWD on SV trim (this one has it)'],
    cons: ['CVT reliability on 2019–2020 Altimas has documented issues — get it inspected', 'Nissan resale value drops faster than Honda/Toyota rivals'],
    why: 'This is a value play, not a safe one. The price is excellent, but the CVT on this model year has a known failure pattern — budget for a pre-purchase inspection (~$150) before you commit.',
    dealDelta: '−$1,400',
    dealComps: '12 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup'],
    tradeoff: 'Best price with a rare AWD-sedan combo but CVT reliability risk needs a PPI first',
    imageUrl: IMAGIN('nissan', 'altima', 2020),
  },
  {
    id: 'mazda320',
    name: '2020 Mazda3 Preferred',
    miles: '31k mi',
    distance: '19 mi away',
    fit: 79,
    deal: 'Good',
    tco: '$355',
    otd: '$18,200',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Bay City Motors · Burlingame',
    pros: ['Best interior quality and driving feel in the compact-sedan class', 'Above-average reliability for the segment', 'Available AWD on this trim'],
    cons: ['Rear visibility is compromised by the sloping roofline', 'Infotainment controlled by rotary dial only, no touchscreen while driving'],
    why: 'Same story as its CX-5 sibling: the Mazda3 drives and feels like a more expensive car. It scores well on deal because Mazda sedans move slower than Camry/Accord in this market, so there\'s real negotiating room.',
    dealDelta: '−$900',
    dealComps: '10 comps',
    mustHaveKeys: ['awd', 'backup'],
    imageUrl: IMAGIN('mazda', 'mazda3', 2020),
  },
  {
    id: 'impreza21',
    name: '2021 Subaru Impreza Premium',
    miles: '27k mi',
    distance: '24 mi away',
    fit: 75,
    deal: 'Fair',
    tco: '$370',
    otd: '$19,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Golden Gate Subaru · SF',
    pros: ['Standard AWD on every trim — rare in a compact sedan', 'Subaru\'s boxer engine and symmetrical AWD are proven long-term', 'Great visibility and an easy-to-place nose for city driving'],
    cons: ['CVT drone under hard acceleration', 'Priced close to market — Subaru holds value well so discounts are thin'],
    why: 'If you want AWD but don\'t want or need an SUV, this is the only sedan on the list that offers it standard. It\'s not a bargain — Subaru CPO pricing rarely moves much — but it\'s the only car here pairing a small footprint with foul-weather capability.',
    dealDelta: '+$150',
    dealComps: '9 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup'],
    tradeoff: 'Only sedan here with standard AWD but priced at market with little room to negotiate',
    imageUrl: IMAGIN('subaru', 'impreza', 2021),
  },
  {
    id: 'elantra22',
    name: '2022 Hyundai Elantra SEL',
    miles: '22k mi',
    distance: '16 mi away',
    fit: 76,
    deal: 'Good',
    tco: '$345',
    otd: '$19,200',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'Concord Hyundai',
    pros: ['10-year/100k powertrain warranty transfers to CPO buyers', 'Sharp styling and a tech-forward cabin for the price', 'Low miles for the year, one owner'],
    cons: ['Hyundai reliability has improved but isn\'t yet Toyota-tier', 'Firmer ride on rough pavement compared to Corolla/Civic'],
    why: 'The Elantra\'s real edge is the warranty — Hyundai\'s 10-year powertrain coverage is transferable and still has 8+ years left on this one. Combined with CPO certification, it\'s one of the lowest-risk budget sedans here.',
    dealDelta: '−$400',
    dealComps: '11 comps',
    mustHaveKeys: ['carplay', 'backup'],
    imageUrl: IMAGIN('hyundai', 'elantra', 2022),
  },
  {
    id: 'forte21',
    name: '2021 Kia Forte GT-Line',
    miles: '29k mi',
    distance: '22 mi away',
    fit: 70,
    deal: 'Good',
    tco: '$330',
    otd: '$17,500',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Serramonte Kia · Colma',
    pros: ['Lowest out-the-door price of any sedan on the list', '10-year/100k powertrain warranty still active (Kia matches Hyundai)', 'GT-Line adds sportier styling and larger wheels at no reliability cost'],
    cons: ['Rear seat is the tightest in the compact-sedan group', 'Road noise is more noticeable than Mazda3/Civic at highway speed'],
    why: 'The Forte is the Elantra\'s twin under the skin with an even lower price. If budget is the top priority and you don\'t need AWD or extra cargo room, this undercuts everything else here by at least $1,700.',
    dealDelta: '−$700',
    dealComps: '8 comps',
    mustHaveKeys: ['carplay', 'backup'],
    tradeoff: 'Lowest price of any sedan here but the smallest rear seat in the group',
    imageUrl: IMAGIN('kia', 'forte', 2021),
  },
  {
    id: 'jetta21',
    name: '2021 Volkswagen Jetta SE',
    miles: '33k mi',
    distance: '20 mi away',
    fit: 68,
    deal: 'Fair',
    tco: '$360',
    otd: '$18,500',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Santa Clara Volkswagen',
    pros: ['European driving feel and a more substantial highway ride than rivals', 'Roomy trunk for the segment', 'Turbocharged engine feels stronger than the spec sheet suggests'],
    cons: ['VW reliability and dealer-service costs trail the segment average', 'Weakest resale value of any sedan on this list'],
    why: 'The Jetta drives like a slightly bigger, more planted car than its compact-sedan classmates. The tradeoff is the same one VW buyers always face: higher long-term maintenance costs and faster depreciation.',
    dealDelta: '+$100',
    dealComps: '7 comps',
    mustHaveKeys: ['carplay', 'backup'],
    imageUrl: IMAGIN('volkswagen', 'jetta', 2021),
  },
  {
    id: 'accordh23',
    name: '2023 Honda Accord Hybrid Sport',
    miles: '12k mi',
    distance: '25 mi away',
    fit: 89,
    deal: 'Fair',
    tco: '$420',
    otd: '$29,800',
    condition: 'Certified pre-owned',
    fuelType: 'Hybrid',
    dealer: 'Peninsula Honda · San Mateo',
    pros: ['44 mpg combined with zero range anxiety', 'Almost new — 1 year old with full factory warranty remaining', 'Quietest, smoothest-riding car on this entire list'],
    cons: ['At the top of the sedan budget range', 'Hybrid battery sits under the trunk floor, slightly reducing cargo depth'],
    why: 'This is what you get if you want RAV4-Hybrid efficiency in a sedan wrapper — 44 mpg with none of the compromises of a plug-in. It\'s priced at market because low-mileage Accord Hybrids are in short supply right now.',
    dealDelta: '+$200',
    dealComps: '6 comps',
    mustHaveKeys: ['carplay', 'backup', 'mpg'],
    tradeoff: 'Best fuel economy of any non-EV sedan but priced at a premium for its low miles',
    imageUrl: IMAGIN('honda', 'accord', 2023),
  },
  {
    id: 'prius21',
    name: '2021 Toyota Prius LE',
    miles: '38k mi',
    distance: '17 mi away',
    fit: 72,
    deal: 'Good',
    tco: '$310',
    otd: '$21,400',
    condition: 'Used',
    fuelType: 'Hybrid',
    dealer: 'CarMax Fremont',
    pros: ['56 mpg combined — best fuel economy of any non-EV on the list', 'Toyota hybrid system has a 20+ year reliability track record', 'Hatchback cargo flexibility despite the small footprint'],
    cons: ['Polarizing styling and firm, economy-focused seats', 'Slowest-accelerating car on this list'],
    why: 'Nothing gas-powered here comes close to the Prius\'s fuel economy, and Toyota\'s hybrid drivetrain is arguably the most proven powertrain in the industry. Right call if minimizing fuel spend matters more than how the car feels to drive.',
    dealDelta: '−$550',
    dealComps: '13 comps',
    mustHaveKeys: ['carplay', 'backup', 'mpg'],
    imageUrl: IMAGIN('toyota', 'prius', 2021),
  },
  {
    id: 'passport21',
    name: '2021 Honda Passport EX-L',
    miles: '28k mi',
    distance: '23 mi away',
    fit: 84,
    deal: 'Good',
    tco: '$470',
    otd: '$29,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'CarMax Oakland',
    pros: ['Standard AWD (i-VTM4) with genuinely useful torque-vectoring for wet roads', 'V6 power — quickest-accelerating gas SUV on this list', 'Two-row layout means more cargo room than 3-row rivals its size'],
    cons: ['23 mpg combined — thirstiest 2-row SUV here', 'No third row if you need occasional extra seating'],
    why: 'The Passport is the CR-V\'s bigger, V6-powered sibling for buyers who don\'t need a third row but want more towing and cargo capacity. Reliability tracks close to the CR-V\'s excellent record, and this one is priced under comps.',
    dealDelta: '−$650',
    dealComps: '9 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup'],
    imageUrl: IMAGIN('honda', 'passport', 2021),
  },
  {
    id: 'highlander21',
    name: '2021 Toyota Highlander XLE',
    miles: '31k mi',
    distance: '26 mi away',
    fit: 86,
    deal: 'Good',
    tco: '$480',
    otd: '$33,500',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'CarMax San Rafael',
    pros: ['Genuine 3-row seating adults can use, not just kids', 'Toyota reliability carries over from RAV4/Camry', 'CPO adds Toyota\'s extended powertrain coverage'],
    cons: ['Third row eats into cargo space when in use', 'Near the top of a 3-row budget'],
    why: 'The Highlander is the safe pick if you need three rows — same reliability DNA as the RAV4 and Camry, just scaled up. The third row is usable by adults for shorter trips, which isn\'t true of every 3-row crossover in this class.',
    dealDelta: '−$700',
    dealComps: '14 comps',
    mustHaveKeys: ['carplay', 'backup', 'thirdrow'],
    imageUrl: IMAGIN('toyota', 'highlander', 2021),
  },
  {
    id: '4runner19',
    name: '2019 Toyota 4Runner SR5',
    miles: '52k mi',
    distance: '31 mi away',
    fit: 79,
    deal: 'Good',
    tco: '$455',
    otd: '$31,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Private Seller · Concord',
    pros: ['Body-on-frame construction — genuinely off-road capable and easy to lift/modify', 'Toyota\'s most bulletproof SUV; 300k-mile examples aren\'t rare', 'Holds resale value better than almost anything in this class'],
    cons: ['18 mpg combined — thirstiest SUV on the list by a wide margin', 'Ride is trucky on-road compared to unibody crossovers'],
    why: 'If you want an SUV that\'s still a truck underneath — capable of real off-roading and holding value for a decade — the 4Runner is unmatched here. You pay for it at the pump.',
    dealDelta: '−$400',
    dealComps: '11 comps',
    mustHaveKeys: ['awd', 'backup'],
    tradeoff: 'Most off-road capable and best resale on the list but the worst fuel economy by far',
    imageUrl: IMAGIN('toyota', '4runner', 2019),
  },
  {
    id: 'sportage22',
    name: '2022 Kia Sportage LX',
    miles: '24k mi',
    distance: '18 mi away',
    fit: 75,
    deal: 'Good',
    tco: '$400',
    otd: '$23,900',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'Serramonte Kia · Colma',
    pros: ['Kia\'s 10-year/100k powertrain warranty still has 9+ years left', 'Redesigned-generation styling and tech punch above the price', 'Roomy cargo area for a compact SUV'],
    cons: ['LX base trim lacks some driver-assist features standard on rivals', 'Kia resale value trails Honda/Toyota by a noticeable margin'],
    why: 'The Sportage undercuts the CR-V and RAV4 by several thousand dollars while carrying a warranty that outlasts them both. The main risk is resale, but that matters less if you keep it long-term.',
    dealDelta: '−$550',
    dealComps: '12 comps',
    mustHaveKeys: ['carplay', 'backup'],
    imageUrl: IMAGIN('kia', 'sportage', 2022),
  },
  {
    id: 'telluride22',
    name: '2022 Kia Telluride EX',
    miles: '26k mi',
    distance: '29 mi away',
    fit: 90,
    deal: 'Fair',
    tco: '$520',
    otd: '$37,500',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'Walnut Creek Kia',
    pros: ['Consistently rated the best 3-row SUV for family use by independent reviewers', 'Genuinely comfortable third row, not an afterthought', 'Loaded EX trim includes most safety tech standard'],
    cons: ['High demand keeps prices firm — little negotiating room', '23 mpg combined, average for the segment'],
    why: 'The Telluride is the best-reviewed 3-row SUV in this price range for a reason — the third row is usable and the interior feels a class above its price. It scores Fair on deal only because demand keeps CPO Tellurides selling near sticker.',
    dealDelta: '+$300',
    dealComps: '8 comps',
    mustHaveKeys: ['carplay', 'backup', 'thirdrow'],
    tradeoff: 'Best-reviewed 3-row SUV on the list but priced at a premium due to demand',
    imageUrl: IMAGIN('kia', 'telluride', 2022),
  },
  {
    id: 'santafe21',
    name: '2021 Hyundai Santa Fe SEL',
    miles: '30k mi',
    distance: '21 mi away',
    fit: 77,
    deal: 'Good',
    tco: '$430',
    otd: '$25,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Concord Hyundai',
    pros: ['Standard AWD at a price below most 2-row rivals', 'Upscale interior design for the price point', 'Hyundai\'s warranty coverage is still active on this model year'],
    cons: ['No third-row option on this generation', 'Reliability data is solid but has a shorter track record than Honda/Toyota'],
    why: 'The Santa Fe undercuts the CR-V and RAV4 on price while matching them on standard AWD and interior quality. Good pick if you\'ve ruled out the Japanese brands on price and don\'t need three rows.',
    dealDelta: '−$500',
    dealComps: '10 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup'],
    imageUrl: IMAGIN('hyundai', 'santa-fe', 2021),
  },
  {
    id: 'palisade22',
    name: '2022 Hyundai Palisade SEL',
    miles: '21k mi',
    distance: '27 mi away',
    fit: 87,
    deal: 'Good',
    tco: '$500',
    otd: '$34,900',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'Concord Hyundai',
    pros: ['Telluride\'s mechanical twin at a similar spec, sometimes better availability', 'Three rows with a genuinely usable second-row captain\'s chairs option', 'CPO adds Hyundai\'s extended powertrain protection'],
    cons: ['23 mpg combined, no better than most gas 3-row rivals', 'Brand resale value trails Toyota/Honda'],
    why: 'Mechanically near-identical to the Telluride (same platform, different skin), the Palisade is often easier to find and occasionally priced better. If you can\'t find a Telluride in your range, this is the direct alternative.',
    dealDelta: '−$450',
    dealComps: '9 comps',
    mustHaveKeys: ['carplay', 'backup', 'thirdrow'],
    imageUrl: IMAGIN('hyundai', 'palisade', 2022),
  },
  {
    id: 'cx921',
    name: '2021 Mazda CX-9 Touring',
    miles: '33k mi',
    distance: '24 mi away',
    fit: 80,
    deal: 'Good',
    tco: '$460',
    otd: '$29,500',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'South Bay Mazda · San Jose',
    pros: ['Best driving dynamics of any 3-row SUV on this list', 'Turbocharged engine feels stronger than its mpg numbers suggest', 'Upscale cabin materials for the price'],
    cons: ['Third row is tight — best for kids, not adults', 'Reliability is good but one tier below Toyota/Honda'],
    why: 'Like the CX-5, the CX-9 is the one to test-drive if you care how a 3-row SUV feels on the road — genuinely engaging compared to the Highlander or Palisade. The third row is the compromise.',
    dealDelta: '−$800',
    dealComps: '7 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup', 'thirdrow'],
    tradeoff: 'Best to drive of any 3-row SUV here but the smallest third row in the group',
    imageUrl: IMAGIN('mazda', 'cx-9', 2021),
  },
  {
    id: 'ascent21',
    name: '2021 Subaru Ascent Premium',
    miles: '35k mi',
    distance: '28 mi away',
    fit: 78,
    deal: 'Good',
    tco: '$475',
    otd: '$28,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Golden Gate Subaru · SF',
    pros: ['Standard AWD across every trim, including base', 'Roomiest 3-row cargo area in this price bracket', 'Subaru\'s 7-year/100k CPO powertrain warranty available'],
    cons: ['Turbocharged flat-4 needs premium fuel for full output', 'Infotainment lags behind Kia/Hyundai\'s newer systems'],
    why: 'The Ascent is Subaru\'s answer for buyers who need three rows and AWD but don\'t want a truck-based SUV. Roomiest cargo-wise of the 3-row options here, though the tech inside feels a generation behind the Telluride\'s.',
    dealDelta: '−$600',
    dealComps: '8 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup', 'thirdrow'],
    imageUrl: IMAGIN('subaru', 'ascent', 2021),
  },
  {
    id: 'crosstrek22',
    name: '2022 Subaru Crosstrek Premium',
    miles: '19k mi',
    distance: '15 mi away',
    fit: 83,
    deal: 'Good',
    tco: '$385',
    otd: '$23,400',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'Golden Gate Subaru · SF',
    pros: ['Standard AWD and 8.7" ground clearance in a compact, easy-to-park footprint', 'Excellent reliability track record for the segment', 'Low miles with CPO warranty still active'],
    cons: ['Base engine is underpowered when loaded with passengers/cargo', 'Cargo area is noticeably smaller than CR-V/RAV4'],
    why: 'If you want AWD capability without stepping up to a full-size crossover, the Crosstrek is the smallest, most efficient way to get it. The tradeoff is cargo room — closer to a tall hatchback than a true SUV.',
    dealDelta: '−$500',
    dealComps: '10 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup'],
    imageUrl: IMAGIN('subaru', 'crosstrek', 2022),
  },
  {
    id: 'traverse21',
    name: '2021 Chevrolet Traverse LT',
    miles: '37k mi',
    distance: '22 mi away',
    fit: 71,
    deal: 'Good',
    tco: '$470',
    otd: '$26,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Concord Chevrolet',
    pros: ['Most third-row and cargo space per dollar of any SUV on this list', 'V6 power with a smooth, quiet highway ride', 'Priced well below Telluride/Highlander for similar interior space'],
    cons: ['GM reliability trails the Japanese and Korean 3-row options', '19 mpg combined — thirstier than most rivals'],
    why: 'The Traverse is the space-per-dollar champion of this list — more interior room than the Telluride or Highlander for thousands less. The reliability gap versus Toyota/Kia is real, so budget for maintenance past year 5.',
    dealDelta: '−$900',
    dealComps: '13 comps',
    mustHaveKeys: ['carplay', 'backup', 'thirdrow'],
    tradeoff: 'Most interior space per dollar on the list but reliability trails Japanese/Korean rivals',
    imageUrl: IMAGIN('chevrolet', 'traverse', 2021),
  },
  {
    id: 'terrain21',
    name: '2021 GMC Terrain SLE',
    miles: '29k mi',
    distance: '20 mi away',
    fit: 68,
    deal: 'Good',
    tco: '$400',
    otd: '$21,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Concord Chevrolet',
    pros: ['One of the lowest-priced AWD compact SUVs on the list', 'Comfortable, quiet ride for daily commuting', 'Turbocharged engine returns decent mpg for the class'],
    cons: ['GM compact-SUV reliability sits below the segment average', 'Interior materials feel a step behind Honda/Toyota'],
    why: 'The Terrain is a budget way into AWD — undercuts the CR-V and RAV4 by several thousand dollars. Better fit if you turn cars over every 3-4 years than if you plan to keep it a decade.',
    dealDelta: '−$700',
    dealComps: '9 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup'],
    imageUrl: IMAGIN('gmc', 'terrain', 2021),
  },
  {
    id: 'edge21',
    name: '2021 Ford Edge SEL',
    miles: '27k mi',
    distance: '25 mi away',
    fit: 69,
    deal: 'Good',
    tco: '$415',
    otd: '$23,500',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Hayward Ford',
    pros: ['Roomy 2-row cargo area, larger than most compact SUVs', 'AWD available and standard on this trim', 'CarPlay/Android Auto standard with a large touchscreen'],
    cons: ['Ford SUV reliability trails Toyota/Honda in independent surveys', 'No 3-row option if your needs grow'],
    why: 'The Edge trades the small footprint of a compact crossover for genuinely useful 2-row cargo space, without stepping up to a 3-row SUV\'s price. Reliability is the tradeoff — a step below the class leaders.',
    dealDelta: '−$550',
    dealComps: '8 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup'],
    imageUrl: IMAGIN('ford', 'edge', 2021),
  },
  {
    id: 'explorer20',
    name: '2020 Ford Explorer XLT',
    miles: '41k mi',
    distance: '30 mi away',
    fit: 70,
    deal: 'Fair',
    tco: '$490',
    otd: '$25,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Hayward Ford',
    pros: ['Rear-wheel-drive-based platform gives it more truck-like towing capacity', 'Roomy third row for the price point', 'Lowest price of any 3-row SUV on this list'],
    cons: ['Early years of this generation had documented reliability issues — check recall history', '17–21 mpg combined depending on drivetrain — thirsty for the segment'],
    why: 'This is the budget 3-row option, but go in with eyes open: the first two model years of this Explorer generation had more reliability complaints than Ford\'s average. Pull a Carfax and verify recall work first.',
    dealDelta: '+$100',
    dealComps: '11 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup', 'thirdrow'],
    tradeoff: 'Cheapest 3-row SUV on the list but this generation\'s early years carry real reliability caveats',
    imageUrl: IMAGIN('ford', 'explorer', 2020),
  },
  {
    id: 'cherokee21',
    name: '2021 Jeep Grand Cherokee Limited',
    miles: '32k mi',
    distance: '24 mi away',
    fit: 74,
    deal: 'Fair',
    tco: '$460',
    otd: '$29,500',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'San Jose Chrysler Jeep',
    pros: ['Genuine off-road/towing capability with a plush on-road ride', 'Limited trim adds leather, panoramic sunroof, and upgraded tech standard', 'CPO adds Jeep\'s extended warranty coverage'],
    cons: ['Stellantis reliability data is below the segment average', '20 mpg combined, thirstier than most 2-row rivals'],
    why: 'The Grand Cherokee blends genuine off-road ability with a genuinely comfortable interior — few SUVs at this price manage both. Reliability surveys put Jeep below average, so lean on the CPO warranty rather than skip it.',
    dealDelta: '+$150',
    dealComps: '7 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup'],
    imageUrl: IMAGIN('jeep', 'grand-cherokee', 2021),
  },
  {
    id: 'wrangler20',
    name: '2020 Jeep Wrangler Sport S',
    miles: '36k mi',
    distance: '19 mi away',
    fit: 65,
    deal: 'Good',
    tco: '$445',
    otd: '$27,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'San Jose Chrysler Jeep',
    pros: ['Removable doors/roof and true 4x4 low-range — unmatched off-road capability here', 'Strong resale value, among the best of any vehicle on this list', 'Huge aftermarket for parts and customization'],
    cons: ['Poor on-road refinement — wind noise and vague steering at freeway speed', '17 mpg combined and little rear cargo room with the top up'],
    why: 'The Wrangler isn\'t a daily-driver SUV in the conventional sense — it\'s a genuine off-roader you can also commute in. If that trade-off appeals to you, nothing else on this list matches its capability or resale value.',
    dealDelta: '−$300',
    dealComps: '9 comps',
    mustHaveKeys: ['awd', 'backup'],
    tradeoff: 'Best off-road capability and resale on the list but the roughest on-road ride by far',
    imageUrl: IMAGIN('jeep', 'wrangler', 2020),
  },
  {
    id: 'tiguan21',
    name: '2021 Volkswagen Tiguan SE',
    miles: '28k mi',
    distance: '21 mi away',
    fit: 67,
    deal: 'Good',
    tco: '$410',
    otd: '$21,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Santa Clara Volkswagen',
    pros: ['Roomiest cabin in the compact-SUV class, close to midsize interior space', 'European-tuned ride and handling', 'Available third-row jump seat (rare in this class)'],
    cons: ['VW reliability and maintenance costs trail Japanese/Korean rivals', 'Weakest resale value of any compact SUV on this list'],
    why: 'The Tiguan is bigger inside than every other compact SUV here, with an optional third-row seat that\'s genuinely unique in this class. The catch is VW\'s reliability and resale reputation, both below the segment average.',
    dealDelta: '−$400',
    dealComps: '6 comps',
    mustHaveKeys: ['carplay', 'backup'],
    imageUrl: IMAGIN('volkswagen', 'tiguan', 2021),
  },
  {
    id: 'atlas21',
    name: '2021 Volkswagen Atlas SE',
    miles: '34k mi',
    distance: '26 mi away',
    fit: 72,
    deal: 'Fair',
    tco: '$475',
    otd: '$26,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Santa Clara Volkswagen',
    pros: ['Largest 3-row interior and cargo area for the price on this list', 'Genuinely usable third row for adults on shorter trips', 'Standard CarPlay/Android Auto on a large touchscreen'],
    cons: ['VW long-term reliability lags the segment', '18 mpg combined, one of the thirstier 3-row options'],
    why: 'Interior space is the Atlas\'s whole pitch — bigger inside than the Highlander or Telluride for less money. Reliability data is why it scores Fair rather than Good; budget for maintenance beyond the warranty period.',
    dealDelta: '+$100',
    dealComps: '5 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup', 'thirdrow'],
    imageUrl: IMAGIN('volkswagen', 'atlas', 2021),
  },
  {
    id: 'xc6020',
    name: '2020 Volvo XC60 Momentum',
    miles: '39k mi',
    distance: '33 mi away',
    fit: 76,
    deal: 'Good',
    tco: '$500',
    otd: '$29,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Peninsula Volvo · Menlo Park',
    pros: ['Top-tier safety engineering — Volvo\'s IIHS/NHTSA scores are consistently class-leading', 'Understated, upscale interior that doesn\'t scream ‘luxury SUV’', 'Standard AWD with genuinely confident handling'],
    cons: ['Maintenance costs run higher than mainstream brands once out of warranty', '22 mpg combined, average for a luxury compact SUV'],
    why: 'If safety engineering is a top priority, Volvo\'s reputation here is deserved — the XC60 consistently earns the best crash-test scores in its class. Priced like a mainstream SUV right now since Volvo values have softened.',
    dealDelta: '−$600',
    dealComps: '6 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup'],
    imageUrl: IMAGIN('volvo', 'xc60', 2020),
  },
  {
    id: 'rx35021',
    name: '2021 Lexus RX 350',
    miles: '25k mi',
    distance: '29 mi away',
    fit: 85,
    deal: 'Fair',
    tco: '$530',
    otd: '$37,900',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'Lexus of Serramonte',
    pros: ['Lexus/Toyota reliability at the top of the luxury-SUV class', 'Whisper-quiet cabin and a long-standing reputation for owner satisfaction', 'CPO adds Lexus\'s comprehensive extended coverage'],
    cons: ['At the top of the budget range for a 2-row SUV', '20 mpg combined — no better than mainstream rivals despite the price'],
    why: 'The RX 350 is essentially a RAV4\'s reliability record wrapped in a genuinely quiet, well-built luxury cabin. Priced at a premium versus mainstream SUVs, but resale value and CPO coverage make the long-term cost more reasonable than it first appears.',
    dealDelta: '+$400',
    dealComps: '7 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup'],
    imageUrl: IMAGIN('lexus', 'rx', 2021),
  },
  {
    id: 'nx21',
    name: '2021 Lexus NX 300',
    miles: '27k mi',
    distance: '24 mi away',
    fit: 81,
    deal: 'Good',
    tco: '$480',
    otd: '$30,900',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'Lexus of Serramonte',
    pros: ['Compact-SUV footprint with Lexus reliability and cabin quality', 'CPO warranty backed by Lexus\'s dealer network', 'Turbocharged engine has more low-end punch than the RX'],
    cons: ['Rear seat and cargo area are tight for the price point', 'Older touchpad-based infotainment system feels dated'],
    why: 'The NX is the smaller, more affordable way into Lexus ownership — same reliability reputation as the RX in a size that\'s easier to park and more efficient. The infotainment interface is its weakest point; test it before you commit.',
    dealDelta: '−$450',
    dealComps: '8 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup'],
    imageUrl: IMAGIN('lexus', 'nx', 2021),
  },
  {
    id: 'rdx21',
    name: '2021 Acura RDX Technology',
    miles: '30k mi',
    distance: '27 mi away',
    fit: 80,
    deal: 'Good',
    tco: '$490',
    otd: '$31,500',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'Acura of Pleasanton',
    pros: ['Honda-grade reliability in a genuinely sporty-handling luxury SUV', 'Technology trim adds a 12-speaker premium audio system and full driver-assist suite standard', 'Turbocharged engine outperforms most rivals in its class'],
    cons: ['Ride is firmer than the Lexus/Volvo alternatives here', 'Resale value trails Lexus, though still better than mainstream brands'],
    why: 'The RDX is the enthusiast\'s pick among the luxury SUVs on this list — corners better than the RX or XC60 while carrying Honda\'s reliability record underneath the Acura badge. The ride firmness is the tradeoff for that handling.',
    dealDelta: '−$500',
    dealComps: '6 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup'],
    tradeoff: 'Sportiest-handling luxury SUV here with Honda-grade reliability but a firmer ride than rivals',
    imageUrl: IMAGIN('acura', 'rdx', 2021),
  },
  {
    id: 'murano20',
    name: '2020 Nissan Murano SV',
    miles: '40k mi',
    distance: '23 mi away',
    fit: 65,
    deal: 'Good',
    tco: '$415',
    otd: '$21,500',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Milpitas Nissan',
    pros: ['Distinctive styling and a genuinely upscale cabin for the price', 'Comfortable, quiet highway ride', 'Lowest price of any 2-row midsize SUV on the list'],
    cons: ['CVT transmission reliability is a documented weak point for this generation', 'Nissan resale value is among the weakest on this list'],
    why: 'The Murano looks and feels more expensive than its price tag, but the CVT is the same family of transmission that\'s caused issues across Nissan\'s lineup this generation. A pre-purchase inspection focused on the transmission is worth the $150.',
    dealDelta: '−$800',
    dealComps: '9 comps',
    mustHaveKeys: ['carplay', 'backup'],
    tradeoff: 'Most upscale-feeling cabin for the price but CVT reliability is a real risk to check before buying',
    imageUrl: IMAGIN('nissan', 'murano', 2020),
  },
  {
    id: 'outlander22',
    name: '2022 Mitsubishi Outlander SE',
    miles: '23k mi',
    distance: '20 mi away',
    fit: 66,
    deal: 'Good',
    tco: '$410',
    otd: '$22,900',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'East Bay Mitsubishi · Fremont',
    pros: ['Standard third row — rare at this price point', '10-year/100k powertrain warranty, longest in the industry', 'Low miles with CPO coverage still active'],
    cons: ['Third row is best for small kids only, tight for anyone else', 'Mitsubishi resale value and dealer network are both smaller than mainstream rivals'],
    why: 'The Outlander is the cheapest way to get a third row on this entire list, backed by the longest powertrain warranty of any manufacturer. The third row itself is small — fine for occasional use, not a real seating replacement.',
    dealDelta: '−$600',
    dealComps: '5 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup', 'thirdrow'],
    tradeoff: 'Cheapest 3-row SUV on the list with the longest warranty but the smallest third row by far',
    imageUrl: IMAGIN('mitsubishi', 'outlander', 2022),
  },
  {
    id: 'tacoma20',
    name: '2020 Toyota Tacoma SR5',
    miles: '44k mi',
    distance: '22 mi away',
    fit: 82,
    deal: 'Good',
    tco: '$460',
    otd: '$30,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Capitol Toyota · San Jose',
    pros: ['Best resale value of any vehicle on this entire list — Tacomas barely depreciate', 'Toyota truck reliability with genuine off-road/towing capability', 'Manageable size for daily driving compared to full-size trucks'],
    cons: ['18 mpg combined and a firm, truck-like ride', 'Back seat is tight in the standard cab configuration'],
    why: 'If you want a truck, the Tacoma is the least risky choice here — holds its value better than almost anything on the road, gas or electric. Ride quality and rear seat space are the honest trade-offs versus a full-size truck.',
    dealDelta: '−$500',
    dealComps: '12 comps',
    mustHaveKeys: ['awd', 'backup'],
    tradeoff: 'Best resale value on the entire list but the firmest ride and tightest back seat of any truck here',
    imageUrl: IMAGIN('toyota', 'tacoma', 2020),
  },
  {
    id: 'tundra19',
    name: '2019 Toyota Tundra SR5',
    miles: '58k mi',
    distance: '34 mi away',
    fit: 75,
    deal: 'Good',
    tco: '$500',
    otd: '$33,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Capitol Toyota · San Jose',
    pros: ['Toyota\'s full-size truck reliability record is the best in the segment by a wide margin', 'V8 power with a proven, simple drivetrain', 'Highest towing capacity of any vehicle on this list'],
    cons: ['15 mpg combined — the thirstiest vehicle on the entire list', 'Interior tech feels dated versus F-150/Silverado'],
    why: 'The Tundra is the truck to buy if you genuinely need to tow or haul regularly and want to minimize mechanical risk — Toyota\'s full-size truck reliability data is unmatched. Fuel cost is the honest downside.',
    dealDelta: '−$700',
    dealComps: '9 comps',
    mustHaveKeys: ['awd', 'backup'],
    imageUrl: IMAGIN('toyota', 'tundra', 2019),
  },
  {
    id: 'f15020',
    name: '2020 Ford F-150 XLT',
    miles: '46k mi',
    distance: '26 mi away',
    fit: 73,
    deal: 'Good',
    tco: '$480',
    otd: '$32,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Hayward Ford',
    pros: ['America\'s best-selling truck — huge parts availability and resale liquidity', 'XLT trim balances work-truck capability with daily-driver comfort', 'Available towing packages rival heavier-duty trucks'],
    cons: ['Ford truck reliability trails Toyota, per independent surveys', '17 mpg combined'],
    why: 'The F-150 is the default choice for a reason — the most versatile truck here, with a huge range of configurations and the deepest used-truck market if you ever need to sell. Reliability data puts it a step behind the Tundra.',
    dealDelta: '−$600',
    dealComps: '15 comps',
    mustHaveKeys: ['backup'],
    imageUrl: IMAGIN('ford', 'f-150', 2020),
  },
  {
    id: 'silverado20',
    name: '2020 Chevrolet Silverado 1500 LT',
    miles: '43k mi',
    distance: '28 mi away',
    fit: 71,
    deal: 'Good',
    tco: '$475',
    otd: '$31,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'Concord Chevrolet',
    pros: ['Comfortable ride quality, among the best in the full-size truck class', 'Strong V8 option with a smooth-shifting transmission', 'Priced competitively against F-150/Tundra'],
    cons: ['GM reliability data is below Toyota/Ford in independent surveys', 'Interior materials feel a step behind Ford\'s latest F-150'],
    why: 'The Silverado rides more smoothly than the F-150 or Tundra, which matters if this is a daily driver as much as a work truck. Reliability puts it a notch below both, so factor maintenance costs into the total-ownership math.',
    dealDelta: '−$550',
    dealComps: '10 comps',
    mustHaveKeys: ['backup'],
    imageUrl: IMAGIN('chevrolet', 'silverado', 2020),
  },
  {
    id: 'ridgeline21',
    name: '2021 Honda Ridgeline RTL',
    miles: '26k mi',
    distance: '25 mi away',
    fit: 83,
    deal: 'Good',
    tco: '$455',
    otd: '$33,900',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'Peninsula Honda · San Mateo',
    pros: ['Unibody platform gives it car-like ride quality unmatched by any truck on this list', 'Honda reliability record — best in the truck segment', 'Lockable in-bed trunk and dual-action tailgate are genuinely useful'],
    cons: ['Lower towing/payload capacity than body-on-frame trucks like Tacoma/F-150', 'No manual 4WD low-range for serious off-roading'],
    why: 'The Ridgeline trades some outright towing capacity for a ride more comfortable than any other truck here — drives more like the Passport than a traditional truck. Most livable daily driver of the group if you rarely tow near the max rating.',
    dealDelta: '−$450',
    dealComps: '6 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup'],
    tradeoff: 'Most comfortable daily-driving truck on the list but the lowest towing capacity of the group',
    imageUrl: IMAGIN('honda', 'ridgeline', 2021),
  },
  {
    id: 'odyssey21',
    name: '2021 Honda Odyssey EX-L',
    miles: '29k mi',
    distance: '24 mi away',
    fit: 85,
    deal: 'Good',
    tco: '$475',
    otd: '$31,900',
    condition: 'Certified pre-owned',
    fuelType: 'Gas',
    dealer: 'Peninsula Honda · San Mateo',
    pros: ['Best-in-class reliability among minivans, and minivans as a category outlast most 3-row SUVs', 'Genuinely usable 3 rows plus more cargo room than any SUV on this list', 'Built-in vacuum and rear-seat entertainment on EX-L trim'],
    cons: ['Minivan styling isn\'t for everyone, even if the practicality is unmatched', 'No AWD option on the Odyssey (Sienna and Pacifica offer alternatives)'],
    why: 'If three rows and maximum practicality are the real priorities, the Odyssey beats every SUV on this list on interior space and reliability. Styling is the only reason it doesn\'t top the list outright.',
    dealDelta: '−$600',
    dealComps: '10 comps',
    mustHaveKeys: ['carplay', 'backup', 'thirdrow'],
    tradeoff: 'Most interior space and best reliability of any 3-row vehicle on the list but no AWD option',
    imageUrl: IMAGIN('honda', 'odyssey', 2021),
  },
  {
    id: 'sienna21',
    name: '2021 Toyota Sienna XLE',
    miles: '24k mi',
    distance: '27 mi away',
    fit: 88,
    deal: 'Fair',
    tco: '$440',
    otd: '$36,900',
    condition: 'Certified pre-owned',
    fuelType: 'Hybrid',
    dealer: 'Berkeley Toyota',
    pros: ['Standard hybrid powertrain — 36 mpg combined, unmatched by any other 3-row vehicle here', 'Available AWD, unusual for a minivan', 'Toyota reliability with a CPO warranty layered on top'],
    cons: ['At the top of the overall budget range', 'No V6 option anymore — some buyers miss the power'],
    why: 'The Sienna is the only minivan or 3-row vehicle on this list that\'s also a hybrid, making it the practicality-and-efficiency pick if budget stretches far enough. Optional AWD is genuinely rare in this segment.',
    dealDelta: '+$250',
    dealComps: '7 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup', 'thirdrow', 'mpg'],
    tradeoff: 'Only hybrid, AWD-capable 3-row vehicle on the list but priced at the top of the range',
    imageUrl: IMAGIN('toyota', 'sienna', 2021),
  },
  {
    id: 'pacifica21',
    name: '2021 Chrysler Pacifica Touring L',
    miles: '32k mi',
    distance: '22 mi away',
    fit: 74,
    deal: 'Good',
    tco: '$460',
    otd: '$26,900',
    condition: 'Used',
    fuelType: 'Gas',
    dealer: 'San Jose Chrysler Jeep',
    pros: ['Stow \'n Go seating folds flat into the floor — unmatched cargo flexibility', 'Lowest price of any minivan on this list', 'Roomiest third row of any 3-row vehicle here'],
    cons: ['Stellantis reliability data trails Honda/Toyota minivans', 'Infotainment and driver-assist tech vary noticeably by trim year'],
    why: 'The Pacifica undercuts the Odyssey and Sienna by thousands while offering the same fold-flat seating flexibility, plus the roomiest third row of anything on this list. Reliability gap versus the Honda/Toyota minivans is the real trade-off.',
    dealDelta: '−$700',
    dealComps: '8 comps',
    mustHaveKeys: ['carplay', 'backup', 'thirdrow'],
    imageUrl: IMAGIN('chrysler', 'pacifica', 2021),
  },
  {
    id: 'model322',
    name: '2022 Tesla Model 3 Long Range',
    miles: '22k mi',
    distance: '19 mi away',
    fit: 86,
    deal: 'Good',
    tco: '$340',
    otd: '$33,900',
    condition: 'Used',
    fuelType: 'Electric',
    dealer: 'Tesla Used Inventory · Fremont',
    pros: ['Longest EPA range on this list (~358 mi) with access to the Supercharger network', 'Standard AWD with quicker acceleration than any gas sedan here', 'Lowest fuel-equivalent running cost if charging at home'],
    cons: ['Panel-gap and paint-quality inconsistencies are more common than on mainstream brands', 'No Apple CarPlay/Android Auto — Tesla\'s own interface only'],
    why: 'The Model 3 has the longest range and best Supercharger access of any EV on this list, plus AWD performance that beats every gas sedan here. The interface is a real adjustment if you\'re used to CarPlay.',
    dealDelta: '−$600',
    dealComps: '14 comps',
    mustHaveKeys: ['awd', 'backup', 'mpg'],
    tradeoff: 'Longest range and best charging network access of any EV here but no CarPlay/Android Auto',
    imageUrl: IMAGIN('tesla', 'model-3', 2022),
  },
  {
    id: 'modely22',
    name: '2022 Tesla Model Y Long Range',
    miles: '25k mi',
    distance: '21 mi away',
    fit: 87,
    deal: 'Fair',
    tco: '$370',
    otd: '$39,900',
    condition: 'Used',
    fuelType: 'Electric',
    dealer: 'Tesla Used Inventory · Fremont',
    pros: ['SUV cargo room and ride height with the Model 3\'s range and Supercharger access', 'Standard AWD, quickest-accelerating SUV on this entire list', 'Frequent over-the-air software updates add features post-purchase'],
    cons: ['Priced at the top of the entire list', 'Same fit/finish inconsistency concerns as the Model 3 — inspect in person'],
    why: 'The Model Y is the SUV version of the Model 3\'s case: best-in-class range and charging access, now in a shape with real cargo room. Only makes sense if EV range and Supercharger access are non-negotiable priorities.',
    dealDelta: '+$300',
    dealComps: '11 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup', 'mpg'],
    imageUrl: IMAGIN('tesla', 'model-y', 2022),
  },
  {
    id: 'bolt22',
    name: '2022 Chevrolet Bolt EV LT',
    miles: '18k mi',
    distance: '17 mi away',
    fit: 78,
    deal: 'Good',
    tco: '$290',
    otd: '$20,900',
    condition: 'Used',
    fuelType: 'Electric',
    dealer: 'Concord Chevrolet',
    pros: ['Lowest price of any EV on this list by a wide margin', '259-mile EPA range — competitive with EVs costing $10k+ more', 'Cheapest to run of anything on this entire list if you charge at home'],
    cons: ['Hatchback cargo room is smaller than every SUV on this list', 'GM paused Bolt production — check battery recall/replacement history on this specific VIN'],
    why: 'The Bolt is the cheapest real EV here, undercutting the Niro EV by $10k with comparable range. The one non-negotiable step: confirm this VIN\'s battery was inspected/replaced under GM\'s 2021 recall program.',
    dealDelta: '−$900',
    dealComps: '9 comps',
    mustHaveKeys: ['backup', 'mpg'],
    tradeoff: 'Cheapest EV on the list by far but confirm the battery-recall service history before buying',
    imageUrl: IMAGIN('chevrolet', 'bolt-ev', 2022),
  },
  {
    id: 'ioniq523',
    name: '2023 Hyundai Ioniq 5 SEL',
    miles: '14k mi',
    distance: '23 mi away',
    fit: 84,
    deal: 'Good',
    tco: '$360',
    otd: '$34,900',
    condition: 'Certified pre-owned',
    fuelType: 'Electric',
    dealer: 'Concord Hyundai',
    pros: ['800V architecture charges 10–80% in about 18 minutes on a DC fast charger', 'Distinctive, spacious interior with a flat floor front and rear', 'CPO adds Hyundai\'s EV-specific extended battery coverage'],
    cons: ['303-mile EPA range is good but trails the Model 3/Y', 'Fewer compatible public fast-chargers today versus Tesla\'s network (NACS adapter needed for Superchargers)'],
    why: 'The Ioniq 5\'s fast-charging speed is genuinely best-in-class — a road-trip stop can be under 20 minutes on the right charger. The catch is charger compatibility outside Hyundai\'s own network.',
    dealDelta: '−$500',
    dealComps: '6 comps',
    mustHaveKeys: ['carplay', 'backup', 'mpg'],
    imageUrl: IMAGIN('hyundai', 'ioniq-5', 2023),
  },
  {
    id: 'ev623',
    name: '2023 Kia EV6 Wind',
    miles: '16k mi',
    distance: '26 mi away',
    fit: 83,
    deal: 'Fair',
    tco: '$365',
    otd: '$35,900',
    condition: 'Certified pre-owned',
    fuelType: 'Electric',
    dealer: 'Walnut Creek Kia',
    pros: ['Shares the Ioniq 5\'s fast-charging platform with sportier styling and handling', 'Standard AWD dual-motor setup on Wind trim', 'Kia\'s EV battery warranty is among the most comprehensive in the industry'],
    cons: ['Rear visibility is compromised by the swept-back roofline', 'Priced close to the Ioniq 5 with a smaller back seat'],
    why: 'The EV6 is mechanically the Ioniq 5\'s cousin — same fast-charging speed and battery tech — with a more athletic driving feel. Comes down to styling and handling preference rather than a clear value gap.',
    dealDelta: '+$150',
    dealComps: '5 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup', 'mpg'],
    imageUrl: IMAGIN('kia', 'ev6', 2023),
  },
  {
    id: 'leaf20',
    name: '2020 Nissan Leaf SV',
    miles: '30k mi',
    distance: '14 mi away',
    fit: 62,
    deal: 'Good',
    tco: '$270',
    otd: '$15,900',
    condition: 'Used',
    fuelType: 'Electric',
    dealer: 'Milpitas Nissan',
    pros: ['Lowest price of any EV — even any car — on this entire list', 'Cheapest to run of any vehicle here if charging at home', 'Simple, proven EV platform with a decade of production history'],
    cons: ['149-mile EPA range on this trim — the shortest of any EV here, tight for anything beyond commuting', 'No active thermal management for the battery — expect faster range loss in hot climates'],
    why: 'The Leaf is the cheapest way into EV ownership by a wide margin, but the range and battery-cooling limitations are real — this is a commuter car, not a road-trip car. Fine if your daily driving is well under 100 miles.',
    dealDelta: '−$1,100',
    dealComps: '8 comps',
    mustHaveKeys: ['backup', 'mpg'],
    tradeoff: 'Cheapest car on the entire list but the shortest range and no active battery cooling',
    imageUrl: IMAGIN('nissan', 'leaf', 2020),
  },
  {
    id: 'machE22',
    name: '2022 Ford Mustang Mach-E Premium',
    miles: '20k mi',
    distance: '25 mi away',
    fit: 79,
    deal: 'Good',
    tco: '$380',
    otd: '$32,900',
    condition: 'Used',
    fuelType: 'Electric',
    dealer: 'Hayward Ford',
    pros: ['Sportiest-handling EV SUV on this list, benefits from Mustang chassis tuning', '290-mile EPA range on the extended-range battery', 'Access to Tesla\'s Supercharger network via NACS adapter (Ford was an early adopter)'],
    cons: ['Ford\'s EV software/infotainment has had more reported glitches than Tesla/Hyundai rivals', 'Frunk is smaller than its SUV shape suggests'],
    why: 'The Mach-E is the EV to test if you want SUV practicality with genuinely sporty handling — tuned more like a performance car than most electric SUVs. Software reliability is the honest weak point.',
    dealDelta: '−$650',
    dealComps: '7 comps',
    mustHaveKeys: ['awd', 'carplay', 'backup', 'mpg'],
    imageUrl: IMAGIN('ford', 'mustang-mach-e', 2022),
  },
  {
    id: 'id421',
    name: '2021 Volkswagen ID.4 Pro',
    miles: '27k mi',
    distance: '18 mi away',
    fit: 73,
    deal: 'Good',
    tco: '$355',
    otd: '$24,900',
    condition: 'Used',
    fuelType: 'Electric',
    dealer: 'Santa Clara Volkswagen',
    pros: ['Lowest price of any compact EV SUV on this list', 'Roomy rear seat and cargo area for the EV-SUV class', '260-mile EPA range, competitive for the price'],
    cons: ['VW\'s infotainment software has a rockier reliability reputation than rivals', 'Fewer years of production history than Tesla/Nissan EVs — long-term data is thinner'],
    why: 'The ID.4 undercuts the Ioniq 5 and EV6 by roughly $10k while offering comparable interior space, making it the value pick among compact EV SUVs. A thorough test drive of the actual tech is worth the time.',
    dealDelta: '−$700',
    dealComps: '6 comps',
    mustHaveKeys: ['carplay', 'backup', 'mpg'],
    imageUrl: IMAGIN('volkswagen', 'id.4', 2021),
  },
];
